spring.application.name=quickmart


# Server Configuration
server.port=8080

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# Logging Configuration
logging.level.org.springframework=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.thymeleaf=DEBUG
logging.level.com.quickmart=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Static Resources Configuration
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**

# JSON File Storage Configuration
app.storage.json.path=src/main/resources/data/prime-members.json
